Fix bug in unit test script

diff --git a/.github/workflows/cpp-unit-tests.yml b/.github/workflows/cpp-unit-tests.yml
--- a/.github/workflows/cpp-unit-tests.yml
+++ b/.github/workflows/cpp-unit-tests.yml
@@ -50,10 +50,17 @@ jobs:
                 
                 # Set CMake to Debug mode
                 cmake -DCMAKE_BUILD_TYPE=Debug ..
-                
                 make
+                
                 # Run tests with Valgrind for memory error checking and check for leaks or errors
                 valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ./runTests 2>&1 | tee valgrind_output.log
+                TEST_EXIT_CODE=${PIPESTATUS[0]}  # Capture ./runTests exit code
+
+                if [ $TEST_EXIT_CODE -ne 0 ]; then
+                  echo "Unit tests failed!"
+                  exit 1
+                fi
+                
                 if grep -q "ERROR SUMMARY: 0 errors from 0 contexts" valgrind_output.log; then
                   echo "No memory leaks or errors detected."
                 else
